export const categories = ['Burgers', 'Chicken', 'Sides', 'Drinks'];

export const fallbackMenu = [
  {
    id: 1,
    name: 'Classic Smash',
    slug: 'classic-smash',
    description: 'Double smashed beef, melted cheese, pickles and house sauce.',
    price: 499,
    category: 'Burgers',
    image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=80',
    featured: true,
    active: true,
    sort_order: 1,
  },
  {
    id: 2,
    name: 'Fire House',
    slug: 'fire-house',
    description: 'Smoky beef, spicy jalapeño sauce, crispy onions and cheddar.',
    price: 599,
    category: 'Burgers',
    image_url: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1200&q=80',
    featured: true,
    active: true,
    sort_order: 2,
  },
  {
    id: 3,
    name: 'Crispy Chicken',
    slug: 'crispy-chicken',
    description: 'Crunchy chicken fillet, creamy slaw, lettuce and signature mayo.',
    price: 549,
    category: 'Chicken',
    image_url: 'https://images.unsplash.com/photo-1606756790138-261d2b21cd75?auto=format&fit=crop&w=1200&q=80',
    featured: true,
    active: true,
    sort_order: 3,
  },
  {
    id: 4,
    name: 'Loaded Fries',
    slug: 'loaded-fries',
    description: 'Golden fries loaded with cheese, house sauce and crispy bits.',
    price: 299,
    category: 'Sides',
    image_url: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    active: true,
    sort_order: 4,
  },
  {
    id: 5,
    name: 'Golden Rings',
    slug: 'golden-rings',
    description: 'Crispy onion rings with a smoky dipping sauce.',
    price: 249,
    category: 'Sides',
    image_url: 'https://images.unsplash.com/photo-1639024471283-03518883512d?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    active: true,
    sort_order: 5,
  },
  {
    id: 6,
    name: 'Vanilla Shake',
    slug: 'vanilla-shake',
    description: 'Cold, creamy vanilla shake topped for the perfect finish.',
    price: 299,
    category: 'Drinks',
    image_url: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?auto=format&fit=crop&w=1200&q=80',
    featured: true,
    active: true,
    sort_order: 6,
  },
];
